(("default" . ((user-emacs-directory . "~/emacs/cfclrk")))
 ("cfclrk" . ((user-emacs-directory . "~/emacs/cfclrk")))
 ("min-straight" . ((user-emacs-directory . "~/emacs/min-straight")))
 ("min-package" . ((user-emacs-directory . "~/emacs/min-package")))
 ("prelude" . ((user-emacs-directory . "~/emacs/prelude"))))
