(("default" . ((user-emacs-directory . "~/emacs/cfclrk")))
 ("cfclrk" . ((user-emacs-directory . "~/emacs/cfclrk")))
 ("cfclrk-emacs-plus" . ((user-emacs-directory . "~/emacs/cfclrk-emacs-plus")))
 ("doom" . ((user-emacs-directory . "~/emacs/doomemacs")))
 ("min-straight" . ((user-emacs-directory . "~/emacs/min-straight")))
 ("min-package" . ((user-emacs-directory . "~/emacs/min-package")))
 ("min-clojure" . ((user-emacs-directory . "~/emacs/min-clojure")))
 ("prelude" . ((user-emacs-directory . "~/emacs/prelude"))))
