tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "d12frosted/emacs-plus"
brew "coreutils"
brew "emacs-plus", args: ["with-xwidgets", "with-imagemagick"]
brew "fish"
brew "findutils"
brew "gnupg"
brew "gnutls"
brew "imagemagick"
brew "jq"
brew "make"
brew "node"
brew "rust-analyzer"
brew "shellcheck"
brew "texinfo"
brew "tmux"
brew "tree"

# Downloads a .pkg file in to $(brew --prefix)/Caskroom/basictex/, need to
# manually run it
cask "basictex"
cask "cljstyle"
cask "zprint"
