tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
brew "autoconf"
brew "coreutils"
brew "fish"
brew "findutils"
brew "gnupg"
brew "gnutls"
brew "imagemagick"
brew "jq"
brew "librsvg"
brew "make"
brew "node"
brew "rust-analyzer"
brew "shellcheck"
brew "texinfo"
brew "tmux"
brew "tree"

# Downloads a .pkg file in to $(brew --prefix)/Caskroom/basictex/, need to
# manually run it
cask "basictex"
cask "cljstyle"
cask "zprint"

# Fira code is nice to have, though I use hasklig right now
brew "svn"
tap "homebrew/cask-fonts"
cask "font-fira-code"
