* System Preferences

** Trackpad

   Tap to click

** Keyboard

   Modiffier Keys -> Remap Caps Lock to Control

** Internet Accounts

   iCloud Drive -> Options -> Check Desktop and Documents

* Applications

**  Finder

   - Preferences -> General -> New Finder windows show: home dir
   - Preferences -> Sidebar -> check Pictures and home dir

** 1Password

   Install native app from App Store.

** Firefox

   Install. Sign in to sync. Sign in (again) to the containers extension.

** Iterm2

   Download from website. Preferences:

   - Theme: minimal
   - Color scheme: smooooth

** Keybase

   Create a new key?

* Set Up New MacOS

** Install [[https://brew.sh/][homebrew]]

   Installing brew also installs the Xcode command line tools.

** Run dotfiles

   #+begin_src sh
     bash -c "$()"
   #+end_src

** Change shell

   #+begin_src sh
     f=$(which fish)
     echo "$f" >> /etc/shells
     chsh -s "$f"
   #+end_src

** Keybase

** Alfred

* TODO

  Update ssh .config link ownership to 600

  Read/link to https://sourabhbajaj.com/mac-setup/

  Need findutils installed before find commands in bootstrap.sh work.

  - Add libxml2 to brew
  - For compiling macOS with json, need to brew install Jansson
  - transient/values.el link does not work if transient dir is not there

  Getting error:
  /Users/chris.clark/.emacs.d exists but it is not chemacs2

  Execute basictex =.pkg= file if =pdflatex= command is not on =$PATH=. Then
  needs a new terminal sesison (installer adds path to =/etc/paths.d=).

** Create ssh keys

   github-home and github-work

   Requires brew openssl to already be installed I think?
