name: Test
on:
  push:
    branches: ["*"]

jobs:
  test:
    runs-on: macOS-latest
    steps:

      - name: Debug
        run: |
          echo $SHELL
          echo $PATH
          for i in $path; do echo $i; done

      - name: Run bootstrap script
        run: bash -c "$(curl -sSL https://raw.githubusercontent.com/cfclrk/dotfiles/master/bootstrap.sh)"
